# Sidebar navigation

- label: "Pesiapan Awal"
  link: "/"

- label: Cek Saldo
  link: "/cek-saldo"

- label: List Produk
  link: "/produk"

- label: Transaksi
  items:
    - label: "Metode POST"
      link: "/transaksi/post"
    - label: "Metode GET"
      link: "/transaksi/get"
    - label: "Via IP (Otomax, IRS, Dll)"
      link: "/transaksi/get-text"

- label: Report / Webhook
  items:
    - label: "via POST / GET"
      link: "/webhook/post"
    - label: "Via IP (Otomax, IRS, Dll)"
      link: "/webhook/get"

- label: Status Transaksi
  items:
    - label: "Metode POST"
      link: "/cek-status/post"
    - label: "Metode GET"
      link: "/cek-status/get"
# - label: Lainnya
#   items:
#     - label: Simulasi API
#       link: "https://documenter.getpostman.com/view/22544220/VUjPGPwm"
